package:
  name: automo
  version: '0.0.2'

source:
   path: .
     
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - h5py
    - dxchange
 
  run:
    - dxchange
    - python
    - numpy
    - h5py
    
test:
  # Python imports
  imports:
    - automo

about:
  home: http://project.readthedocs.org
  license: BSD-3
  summary: 'Add docs to any project.'
