#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
AuTomo with Tomosaic.
"""

import tomosaic
import time
try:
    from mpi4py import MPI
except:
    from tomosaic.util.pseudo import pseudo_comm
try:
    from mosaic_meta import *
except:
    try:
        reader = open(os.path.join('tomosaic_misc', 'meta'), 'rb')
        prefix, file_grid, x_shift, y_shift = pickle.load(reader)
        reader.close()
    except:
        raise IOError('Metadata file not found in current working diretory.')
import os
import sys
import argparse


try:
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()
    name = MPI.Get_processor_name()
except:
    comm = pseudo_comm()
    rank = 0
    size = 1


def main(arg):

    parser = argparse.ArgumentParser()
    parser.add_argument("--ds", help="downsample levels, separated by comma",default='1,2,4')
    args = parser.parse_args()
    ds = args.ds
    ds = [int(i) for i in ds.split(',')]

    t0 = time.time()
    tomosaic.reorganize_dir(file_list, raw_ds=ds)

    print('Total time: {}s'.format(time.time() - t0))


if __name__ == "__main__":
    main(sys.argv[1:])