#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
AuTomo example to generage sample previews.
"""

from __future__ import print_function

import argparse
import os
import sys
from os.path import expanduser
import dxchange
import warnings
import numpy as np
from glob import glob
import re, shutil
from tqdm import tqdm
import automo
import automo.util as util
import automo.robo

    
def main(arg):

    parser = argparse.ArgumentParser()
    parser.add_argument("--prefix", help="existing recon foldername", default='')
    parser.add_argument("--shift", help="shift between datasets", default='auto')
    parser.add_argument("--new_folder",help="target folder", default='auto')
    parser.add_argument("--params_file",help="parameter file location", default='auto')
    parser.add_argument("--ini_path",help="ini file location", default='auto')
    parser.add_argument("--ini_name",help="ini filename", default='automo.ini')
    args = parser.parse_args()
    
    params_file = args.params_file
    if params_file == 'auto':
        params_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'automo_params.csv')
    ini_path = args.ini_path
    ini_name = args.ini_name
    if ini_path == 'auto': ini_path = None
    kwargs = util.get_parameters(params_file)

    automo.robo.process_folder(os.getcwd(),
                               ini_path=ini_path,
                               ini_name=ini_name,
			                   check_usage=False,
                               **kwargs)


if __name__ == "__main__":
    main(sys.argv[1:])